builders:
  artifact:
    import: "package:artifact_gen/artifact_gen.dart"
    builder_factories: ["artifactBuilderBuildRunner"]
    build_extensions: { r"$lib$": ["gen/artifacts.gen.dart","gen/exports.gen.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen:combining_builder"]
targets:
  $default:
    builders:
      artifact|artifact:
        enabled: true
